# decimal functions
# 1.srqt ()
# 2. exp()
import decimal
a = decimal.Decimal(4.5).exp()
b = decimal.Decimal(4.5).sqrt()
print("The exponential of decimal number is :",end="")
print(a)
print("The square root of decimal number is :", end="")
print(b)
print("******************************************************************")
# 3. ln()
# 4. log 10()
import decimal
a = decimal. Decimal(4.5).ln()
b = decimal.Decimal(4.5).sqrt()
print("The natural algorithm of decimal number is :",end="")
print(a)
print("The log(base10) of decimal number is :", end="")
print(b)
print("******************************************************************")
# 5. as_tuple(
# 6. fma(a,b)
import decimal
a = decimal. Decimal(-4.5).as_tuple()
b = decimal.Decimal(5).fma(2,3)
print("The tuple form of decimal number is :",end="")
print(a)
print("The fused multiply and addiction of decimal number is :", end="")
print(b)
print("******************************************************************")
# 7. compare()
# 8. compare_total_mag()
import decimal
a = decimal. Decimal(9.53)
b = decimal.Decimal(-9.56)
print("The result of comparison using compare() is :", end="")
print(a.compare(b))
print("The result of comparison using compare_total_mag() is :", end="")
print(a.compare_total_mag(b))
print("******************************************************************")
a = decimal. Decimal(9.53)
b = decimal.Decimal(-9.56)
print("The absolute value using copy_abs() is :", end="")
print(b.copy_abs())
print("The negated value using copy_negate() is :", end="")
print(b.copy_negate())
print("******************************************************************")
