import requests
str_request = requests.get("https://www.w3schools.com/python/")
print(str_request)
print('___________________________________________________')
# print(str_request.content)
print('___________________________________________________')
print(str_request.url)
print('___________________________________________________')
print(str_request.status_code)
print('___________________________________________________')
print(str_request.headers)
print('___________________________________________________')
print(str_request.encoding)
print('___________________________________________________')
print(str_request.elapsed)
print('___________________________________________________')
print(str_request.history)
print('___________________________________________________')
print(str_request.close())
print('___________________________________________________')
print(str_request.cookies)
print('___________________________________________________')
print(str_request.is_redirect)
print('___________________________________________________')
print(str_request.iter_content())
print('___________________________________________________')
print(str_request.iter_lines())
print('___________________________________________________')
print(str_request.reason)
print('___________________________________________________')
print(str_request.ok)
print('___________________________________________________')
print(str_request.links)
print('___________________________________________________')
print(str_request.text)
