string = 'various string methods 1'
string2 = 'investment in learning'
print("lower()")
print(string.lower())
print("upper()")
print(string.upper())
print("islower()")
print(string.islower())
print("isupper()")
print(string.isupper())
print("startswith")
print(string.startswith("var"))
print("endswith")
print(string.endswith("el"))
print("join()")
print('-->'.join(['various', 'strings', 'methods']))
print("split()")
print(string.split())
print("ljust")
print("hello". ljust(15, '*'))
print("r just")
print("hello". rjust(15, '*'))
print("center()")
print("welcome". center(20, '*'))
print("strip()>")
print(string2.strip())
print("l strip()")
print(string2.lstrip())
print("r strip()")
print(string2.rstrip())
