a = int(input("enter any number:"))
print("="*20)
print(float(a))
print("="*20)
print(complex(a))
print("="*20)
print(bin(a))
print("="*20)
print(id(a))
print("="*20)
print(type(a))
print("="*20)
print(bool(a))
print("="*20)
print(chr(a))
print("="*20)
